modLoader="javafml" # mandatory
loaderVersion="[45,)" # Forge for 1.19.4 starts at 45.x
license="MIT"
# Optional: replace with a real link later
# issueTrackerURL="https://github.com/yourname/yourmod/issues"

[[mods]]
modId="pride"
version="1.4.0"
displayName="Warrior's Pride"
authors="Natsu91"
description='''
A mod that replace the whole PvP system, to try to
revert it back to what it was in 1.8.9 / 1.7.10
Pride is the only reason you stand
'''

[[dependencies.pride]]
modId="forge"
mandatory=true
versionRange="[45,)" # Forge 45.x = 1.19.4
ordering="NONE"
side="BOTH"

[[dependencies.pride]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"

[[mixins]]
    config="mixins.pride.json"
